apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gnmsy2xnc-python
  janus-idp.io/tekton: gnmsy2xnc-python
  backstage.io/kubernetes-id: gnmsy2xnc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gnmsy2xnc-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
